# Generated by Django 5.0.7 on 2024-07-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_banner_is_featured_cartorder_cartorderitems_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7. ProductAttributes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
